package com.example.domain.models.album

data class Album(
    val artist: AlbumArtist,
    val available: Boolean,
    val contributors: List<AlbumContributor>,
    val cover: String,
    val coverBig: String,
    val cover_medium: String,
    val cover_small: String,
    val cover_xl: String,
    val duration: Int,
    val fans: Int,
    val genre_id: Int,
    val genres: AlbumGenres,
    val id: Int,
    val link: String,
    val md5_image: String,
    val nb_tracks: Int,
    val record_type: String,
    val release_date: String,
    val title: String,
    val tracklist: String,
    val tracks: AlbumTracks,
    val type: String,
)